apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: banking-ms-ds
  labels:
    app: banking-ms-app
spec:
  template:
    metadata:
      labels:
        app: banking-ms-app
    spec:
      containers:
        - name: nginx-banking-ms-app-container
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
      nodeSelector:
        <any one-node's-labels>: it's value ?
