# To encrypt the sensetive value
apiVersion: v1
kind: Secret
metadata:
  name: njr-eb-ms-app-cred
data: # command: echo -n "ubuntu" | base64, command: echo -n "admin", command: echo -n "cloudblitz" | base64 | base64  --> get encrypt value from server
  mysql_password: <echo-cbz-password-from-terminal>
  mysql_user: <echo-admin-password-from-terminal>

# kubectl apply -f secret.yml
# kubectl get secrets (list: jr-eb-ms-app-cred with 2 data)
  # o/p --> njr-eb-ms-app-cred [2]
# kubectl describe <secret-name>


# Now, edit the file ss-manifest.yml file according to encrypted form in secrets.yml 
    